# Generated by Django 3.1.2 on 2020-10-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('groom_name', models.CharField(max_length=64)),
                ('bride_name', models.CharField(max_length=64)),
                ('design', models.CharField(choices=[('DESIGN_1', 'Design 1'), ('DESIGN_2', 'Design 2'), ('DESIGN_3', 'Design 2'), ('DESIGN_4', 'Design 4')], default='Design 1', max_length=10)),
                ('city', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('slug', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
