# Generated by Django 3.1.2 on 2020-10-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_image', models.ImageField(default='woman1.jpg', upload_to='')),
                ('groom_image', models.ImageField(default='groom.jpg', upload_to='')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='page.page')),
            ],
        ),
    ]
